### ISSUE TITLE
Convert HTTP-URI of material citations

### ISSUE THREAD

**Issue by retog** [plazi/gg2rdf#1]
Example in XML:

    <materialsCitation collectingDate="2015-01-01" collectingDateMax="2015-12-31" collectingDateMin="2015-01-01" collectionCode="RMNH" country="Malaysia" httpUri="http://data.biodiversitydata.nl/naturalis/specimen/RMNH.5003937" location="Kinabatangan Valley" municipality="Sabah" specimenCode="RMNH.5003937" specimenCount="1" stateProvince="Sandakan Province" typeStatus="holotype">

https://github.com/plazi/treatments-xml/blob/98e9fa2e5c49b1dc06993da2b8085d18f2b9c00b/data/02/A9/1B/02A91B5B7C06D177F17192E67A26BAA1.xml#L72

**Comment by nleanba** [comment]
Should this URI be used as the identifier (URI) for the respective citations or should we use the ones that resolve to the citation within the page for the treatment (AFAIK are those based on the UUID → https://github.com/plazi/treatments-xml/issues/11)?

If not used as identifier, under which property should this httpUri be linked?

**Comment by nleanba** [comment]
closed in v1.5
