### ISSUE TITLE
Link to catalogueoflife rather than literal dwc:ID-Col

### ISSUE THREAD

**Issue by retog** [plazi/gg2rdf#10]
The RDF currently use an undefined property http://rs.tdwg.org/dwc/terms/ID-Col pointing to literal representing the catalogueoflife ID. Instead it should use a defined property an point to the catalogueoflife URi (e.g. https://www.catalogueoflife.org/data/taxon/35X2)

**Comment by retog** [comment]
Finding 105439 statement with dwc:ID-CoL as predicate, but not where it is coming from.

**Comment by retog** [comment]
This line 
https://github.com/plazi/treatments-rdf/blob/f2a3f480cc10c0dbd937563f74b1a362682bc57d/data/00/49/C9/0049C912FFADAE16FC92FE733896F55F.ttl#L39
appears to have been added just 3 months ago.

**Comment by retog** [comment]
It appears the property name is taken from the XML attribute name of the taxonomicName Element.

Possibly here: https://github.com/plazi/gg2rdf/blob/4875932ecb21c9592f1ce7040af8f56090d0f5a2/src/gg2rdf.xslt#L579

**Comment by retog** [comment]
The XSLT has been adapted. Left to be done is a SPARQL-Update to change the existing RDF.

**Comment by retog** [comment]
```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX dwc: <http://rs.tdwg.org/dwc/terms/>
INSERT {?g {?s rdfs:seeAlso ?uri} } WHERE {GRAPH ?g {?s dwc:ID-CoL ?o} BIND(iri(concat("https://www.catalogueoflife.org/data/taxon/",?o)) AS ?uri) }
```

**Comment by retog** [comment]
@nleanba did you manage to run the SPARQL to update the existing

**Comment by retog** [comment]
The now generated RDF contains "rdf:seeAlso" rather than "rdfs:seeAlso" https://github.com/plazi/gg2rdf/commit/2f1484edbec6c41ffe11840b30a8b3ea25bf5c27 was however correct.

**Comment by nleanba** [comment]
> @nleanba did you manage to run the SPARQL to update the existing

@retog hat do you mean by that exactly?
